GET https://tribu-ti-staffing-desarrollo-afangwbmcrhucqfh.z01.azurefd.net/ipf-msa-productosfinancieros/bp/products HTTP/1.1
Content-Type: application/json
authorId: 3

###

POST https://tribu-ti-staffing-desarrollo-afangwbmcrhucqfh.z01.azurefd.net/ipf-msa-productosfinancieros/bp/products HTTP/1.1
Content-Type: application/json
authorId: 3

{
    "id": "trj-card 23",
    "name": "Tarjetas de credito",
    "description": "Tarjeta de consumo bajo la modalidad de credito",
    "logo": "https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg",
    "date_release": "2023-02-01",
    "date_revision": "2024-02-01"
}

###

PUT https://tribu-ti-staffing-desarrollo-afangwbmcrhucqfh.z01.azurefd.net/ipf-msa-productosfinancieros/bp/products HTTP/1.1
Content-Type: application/json
authorId: 3

{
    "id": "trj-card",
    "name": "Tarjetas de credito",
    "description": "Tarjeta de consumo bajo la modalidad de credito",
    "logo": "https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg",
    "date_release": "2023-02-01",
    "date_revision": "2024-02-01"
}

###

DELETE https://tribu-ti-staffing-desarrollo-afangwbmcrhucqfh.z01.azurefd.net/ipf-msa-productosfinancieros/bp/products?id=trj-car HTTP/1.1
Content-Type: application/json
authorId: 3

###

GET https://tribu-ti-staffing-desarrollo-afangwbmcrhucqfh.z01.azurefd.net/ipf-msa-productosfinancieros/bp/products/verification?id=trj-card HTTP/1.1
Content-Type: application/json
authorId: 3